package by.pvt.constants;


public enum Commands {
    // команды клиента
    LOGIN, REGISTRY, FORGOT, EDIT_CLIENT, LOGOUT, GO_TO_REGISTRATION, FORGOT_PASSWORD, GET_ORDERS, GO_TO_ORDERS,
    GO_TO_EDIT_CLIENT, GO_TO_CLIENT_PAGE, GET_ALL_CLIENT_ORDERS, DELETE_ORDER, GO_TO_DELETE_ORDER,
    // команды для автомобилей
    GET_ALL_CARS, GET_CAR, ALL_CAR, CAR, LIST_OF_ALL_CARS,
    //команды фильтра
    GO_TO_RENT_CAR_BY_BRAND, RENT_CAR_BY_BRAND, GO_TO_RENT_ALL_CARS, RENT_ALL_CARS,
    GO_TO_RENT_CAR_BY_PRICE, RENT_CAR_BY_PRICE, GO_TO_RENT_CAR_BY_TRANSMISSION, RENT_CAR_BY_TRANSMISSION,
    // общие команды
    CONTACTS, SET_LOCALE_RU, SET_LOCALE_EN,
    //команды администратора
    GO_TO_ADMIN_PAGE, GO_GET_ALL_ORDERS, GO_ADD_NEW_CAR, GO_GET_ALL_USERS, GET_ALL_ORDERS, ADD_NEW_CAR, GET_ALL_USERS

}
